import {useMemo,useState} from 'react';
import {Link,useLocation} from 'react-router-dom';
import DashboardLayout from '../components/DashboardLayout';
import SmartTable from '../components/SmartTable';
import Icon from '../components/Icon';
import {getLedger,getCommissionRules,saveCommissionRules,calculateOrderPricing,getOrders,recordLedgerEntry,addNotification,getSubscription,setSubscription} from '../services/mvecStore';
import {products,vendors} from '../data';
import {useLanguage} from '../context/LanguageContext';
import {useToast} from '../components/Toast';

const money=n=>new Intl.NumberFormat('en-RW').format(Number(n)||0)+' RWF';
const dmy=d=>new Date(d).toLocaleDateString('en-GB');
const read=(k,f)=>{try{const v=JSON.parse(localStorage.getItem(k));return v??f}catch{return f}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));

function Header({eyebrow,title,desc,action}){return <div className="dash-page-head"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{desc}</p></div>{action}</div>}
function Metric({label,value,sub,icon='chart'}){return <div className="metric"><div className="metric-icon"><Icon name={icon}/></div><div><span>{label}</span><strong>{value}</strong><small>{sub}</small></div></div>}

export function CommissionRules(){
 const [rules,setRules]=useState(()=>getCommissionRules()); const toast=useToast();
 const update=(i,key,value)=>setRules(r=>r.map((x,n)=>n===i?{...x,[key]:value}:x));
 const save=()=>{saveCommissionRules(rules);toast.success('Commission rules saved.')};
 const example=calculateOrderPricing({price:50000,category:'Electronics',vendorId:1,delivery:3000,discount:0});
 const addRule=()=>setRules(r=>[...r,{id:`RULE-${Date.now()}`,scope:'Category',target:'New category',rate:5,status:'Active'}]);
 return <DashboardLayout admin><Header eyebrow="FINANCE · COMMISSIONS" title="Commission rules" desc="Set marketplace commission rules by category, vendor, product or promotion." action={<div className="row-actions"><button className="outline-btn" onClick={addRule}>Add rule</button><button className="gradient-btn" onClick={save}>Save rules</button></div>}/><div className="data-card"><div className="data-card-head"><div><h3>Active rules</h3><span>The most specific matching rule is used.</span></div></div><SmartTable columns={[{key:'scope',label:'Scope',render:r=><select className="inline-table-input" value={r.scope} onChange={e=>update(rules.indexOf(r),'scope',e.target.value)}><option>Platform</option><option>Category</option><option>Vendor Type</option><option>Vendor</option><option>Product</option><option>Promotion</option></select>},{key:'target',label:'Target',render:r=><input className="inline-table-input" value={r.target} onChange={e=>update(rules.indexOf(r),'target',e.target.value)}/>},{key:'rate',label:'Commission %',render:r=><input className="inline-table-input" type="number" min="0" max="100" step="0.1" value={r.rate} onChange={e=>update(rules.indexOf(r),'rate',e.target.value)}/>},{key:'status',label:'Status',render:r=><button className={'status '+(r.status==='Active'?'active':'warning')} onClick={()=>update(rules.indexOf(r),'status',r.status==='Active'?'Paused':'Active')}>{r.status}</button>}]} rows={rules} rowKey={r=>r.id} searchPlaceholder="Search commission rules…"/></div><div className="dash-grid"><div className="data-card"><h3>Customer-facing price</h3><p className="tiny">Delivery and applicable marketplace charges are included in the total shown to the buyer.</p><div className="price-summary"><span>Total price</span><strong>{money(example.buyerTotal)}</strong></div></div><div className="data-card"><h3>Internal settlement</h3><p className="tiny">Authorized staff can see the accounting breakdown used for settlement.</p><div className="breakdown"><span>Base product <b>{money(example.basePrice)}</b></span><span>MVEC commission <b>{money(example.mvecCommission)}</b></span><span>Delivery allocation <b>{money(example.delivery)}</b></span><span>Vendor settlement <b>{money(example.vendorSettlement)}</b></span></div></div></div></DashboardLayout>
}

export function FinancialLedger(){
 const toast=useToast();
 const [rows,setRows]=useState(()=>{const existing=getLedger();if(existing.length)return existing;const orders=getOrders();return orders.map(o=>({id:o.transactionId||o.id,createdAt:o.date||new Date().toISOString(),type:'ORDER',orderId:o.id,amount:o.total||0,status:o.settlementStatus||'PENDING'}))});
 const recordReview=()=>{const entry=recordLedgerEntry({type:'MANUAL_REVIEW',orderId:'',transactionId:`MVEC-TXN-${Date.now()}`,amount:0,status:'RECORDED',note:'Ledger review entry'});setRows(getLedger());toast.success('Ledger entry recorded.')};
 return <DashboardLayout admin><Header eyebrow="FINANCE · LEDGER" title="Financial ledger" desc="Every order, payment, settlement, commission and adjustment is traceable from one record." action={<button className="outline-btn" onClick={recordReview}>Record ledger entry</button>}/><div className="metric-grid"><Metric label="Ledger records" value={rows.length} sub="Auditable events" icon="box"/><Metric label="Held funds" value={money(rows.filter(x=>x.status==='HELD').reduce((s,x)=>s+Number(x.amount||0),0))} sub="Protected settlement" icon="wallet"/><Metric label="Released" value={money(rows.filter(x=>x.status==='RELEASED').reduce((s,x)=>s+Number(x.amount||0),0))} sub="Completed settlements" icon="check"/></div><div className="data-card"><SmartTable columns={[{key:'id',label:'Ledger ID'},{key:'type',label:'Event'},{key:'orderId',label:'Order'},{key:'amount',label:'Amount',render:r=>money(r.amount)},{key:'status',label:'Status',render:r=><span className={'status '+(r.status==='RELEASED'?'active':'warning')}>{r.status}</span>},{key:'createdAt',label:'Date',render:r=>dmy(r.createdAt)}]} rows={rows} rowKey={r=>r.id} searchPlaceholder="Search ledger records…"/></div></DashboardLayout>
}

export function AdminAnalytics(){
 const orders=getOrders(); const completed=orders.filter(o=>o.status==='Completed'||o.deliveryStatus==='Delivered'); const gmv=orders.reduce((s,o)=>s+Number(o.total||0),0); const refunds=read('mvec_buyer_refunds',[]);
 const vendorRows=vendors.map(v=>({vendor:v.name,orders:orders.filter(o=>o.vendor===v.name).length,sales:orders.filter(o=>o.vendor===v.name).reduce((s,o)=>s+Number(o.total||0),0),rating:v.rating}));
 return <DashboardLayout admin><Header eyebrow="SUPER ADMIN · ANALYTICS" title="Marketplace analytics" desc="Track marketplace performance across buyers, vendors, suppliers, affiliates and delivery."/><div className="metric-grid"><Metric label="GMV" value={money(gmv||85500000)} sub="Gross merchandise value" icon="chart"/><Metric label="Orders" value={orders.length||2850} sub="All recorded orders" icon="cart"/><Metric label="Completed" value={completed.length||2140} sub="Successfully delivered" icon="check"/><Metric label="Refund rate" value={`${orders.length?((refunds.length/orders.length)*100).toFixed(1):'2.4'}%`} sub="Refund requests / orders" icon="wallet"/><Metric label="Active users" value="125,420" sub="Marketplace accounts" icon="users"/><Metric label="Average order" value={money(orders.length?gmv/orders.length:30000)} sub="Average order value" icon="chart"/></div><div className="data-card"><div className="data-card-head"><div><h3>Vendor performance</h3><span>Orders, sales and rating</span></div></div><SmartTable columns={[{key:'vendor',label:'Vendor'},{key:'orders',label:'Orders'},{key:'sales',label:'Sales',render:r=>money(r.sales)},{key:'rating',label:'Rating',render:r=>`★ ${r.rating}`},{key:'status',label:'Status',render:()=> <span className="status active">Active</span>}]} rows={vendorRows} rowKey={r=>r.vendor} searchPlaceholder="Search vendor performance…"/></div></DashboardLayout>
}

export function CommunicationPage({role}){
 const toast=useToast();
 const defaults=role==='supplier'?[{id:'CON-SUP-1',reference:'SUP-2026-1001',with:'Kigali Tech Store',topic:'Supply order',last:'Please confirm the delivery time.',unread:2,date:'31/08/2026'}]:role==='vendor'?[{id:'CON-VEN-1',reference:'MVEC-HEADPHONES-2026-0001',with:'Aline Uwase',topic:'Order delivery',last:'I will be available for delivery.',unread:1,date:'31/08/2026'}]:[{id:'CON-BUY-1',reference:'MVEC-HEADPHONES-2026-0001',with:'Kigali Tech Store',topic:'Order',last:'Your order is being prepared.',unread:1,date:'31/08/2026'}];
 const [conversations,setConversations]=useState(()=>read(`mvec_conversations_${role}`,defaults)); const [selected,setSelected]=useState(conversations[0]); const [text,setText]=useState(''); const [recipient,setRecipient]=useState(''); const people=read('mvec_users',[{id:'u3',fullName:'MVEC Administrator',email:'admin@mvec.rw',telephone:'+250788100003',role:'super_admin'},{id:'u1',fullName:'Aline Uwase',email:'buyer@mvec.rw',telephone:'+250788100001',role:'buyer'},{id:'u2',fullName:'Eric Mugabo',email:'vendor@mvec.rw',telephone:'+250788100002',role:'vendor'},{id:'u4',fullName:'Rwanda Wholesale Supplier',email:'supplier@mvec.rw',telephone:'+250788100004',role:'supplier'},{id:'u5',fullName:'MVEC Affiliate Network',email:'affiliate@mvec.rw',telephone:'+250788100005',role:'affiliate'},{id:'u6',fullName:'MVEC Delivery Team',email:'delivery@mvec.rw',telephone:'+250788100006',role:'delivery'}]);
 const messages=read(selected?`mvec_messages_${role}_${selected.id}`:'mvec_messages_none',[{from:'other',text:selected?.last||'Welcome to the conversation.',date:selected?.date||dmy(new Date())}]);
 const [thread,setThread]=useState(messages);
 const send=()=>{if(!text.trim()||!selected)return;const next=[...thread,{from:'me',text:text.trim(),date:dmy(new Date())}];setThread(next);write(`mvec_messages_${role}_${selected.id}`,next);setText('');setConversations(cs=>cs.map(c=>c.id===selected.id?{...c,last:text.trim(),unread:0,date:dmy(new Date())}:c));toast.success('Message sent.');addNotification({role,recipient:selected.with,type:'message',title:'New message',message:`New message for ${selected.reference}.`,reference:selected.reference});}; const startConversation=()=>{const person=people.find(x=>x.id===recipient);if(!person)return;const c={id:`CON-${Date.now()}`,reference:`DIRECT-${Date.now()}`,with:person.fullName,topic:'Direct message',last:'New conversation',unread:0,date:dmy(new Date()),phone:person.telephone};setConversations(cs=>[c,...cs]);setSelected(c);setThread([]);setRecipient('');toast.info('Conversation started.');};
 return <DashboardLayout admin={role==='admin'}><Header eyebrow={`${role.toUpperCase()} · COMMUNICATION`} title="Messages" desc="Keep conversations connected to the order or supply transaction they belong to."/><div className="communication-layout"><div className="data-card conversation-list"><div className="new-conversation"><select value={recipient} onChange={e=>setRecipient(e.target.value)}><option value="">Message a user…</option>{people.filter(p=>p.role!==role).map(p=><option key={p.id} value={p.id}>{p.fullName} · {p.role}</option>)}</select><button className="outline-btn" onClick={startConversation} disabled={!recipient}>Start</button></div>{conversations.map(c=><button key={c.id} className={'conversation-item '+(selected?.id===c.id?'selected':'')} onClick={()=>{setSelected(c);setThread(read(`mvec_messages_${role}_${c.id}`,[{from:'other',text:c.last,date:c.date}]))}}><div><b>{c.with}</b><small>{c.reference}</small><p>{c.last}</p></div>{c.unread>0&&<span className="nav-count">{c.unread}</span>}</button>)}</div><div className="data-card message-thread"><div className="thread-head"><div><h3>{selected?.with||'Conversation'}</h3><small>{selected?.reference} {selected?.phone&&` · ${selected.phone}`}</small></div><div className="thread-actions"><Link className="outline-btn" to={role==='delivery'?'/delivery':role==='admin'?'/admin/deliveries':selected?.reference?.startsWith('SUP-')?'/supplier/delivery':'/vendor/delivery'}>Track</Link>{selected?.phone&&<a className="outline-btn" href={`sms:${selected.phone}`}>SMS</a>}</div></div><div className="message-list">{thread.map((m,i)=><div key={i} className={'message-bubble '+(m.from==='me'?'mine':'theirs')}><p>{m.text}</p><small>{m.date}</small></div>)}</div><div className="message-compose"><input value={text} onChange={e=>setText(e.target.value)} placeholder="Write a message…" onKeyDown={e=>e.key==='Enter'&&send()}/><button className="gradient-btn" onClick={send}>Send</button></div></div></div></DashboardLayout>
}

export function BuyerSubscription(){
 const [active,setActive]=useState(()=>getSubscription('buyer')==='premium'); const toast=useToast();
 const toggle=()=>{const next=!active;setSubscription('buyer',next?'premium':'free');setActive(next);toast.success(next?'Premium buyer activated.':'Premium buyer plan cancelled.')};
 return <><Header eyebrow="BUYER" title="Ad removal" desc="Choose whether to reduce non-critical marketplace advertising. Checkout, payment and order tracking remain available either way."/><div className="dash-grid"><div className="data-card"><span className="eyebrow">FREE BUYER</span><h2>RWF 0</h2><p>Standard marketplace experience with relevant sponsored content.</p><ul className="simple-list"><li>Shop all products</li><li>Checkout without interruption</li><li>Order tracking</li></ul><span className={'status '+(!active?'active':'warning')}>{!active?'Current':'Available'}</span></div><div className="data-card"><span className="eyebrow">PREMIUM BUYER</span><h2>RWF 5,000 / month</h2><p>Reduced non-critical advertising while keeping all marketplace functions available.</p><button className={active?'outline-btn':'gradient-btn'} onClick={toggle}>{active?'Cancel plan':'Choose premium'}</button></div></div></>;
}

export function AcquisitionPage({type='supplier'}){
 const supplier=type==='supplier'; const rows=read(`mvec_${type}_acquisition`,supplier?[{id:'LEAD-001',business:'Rwanda Wholesale Suppliers',contact:'+250 788 100 006',category:'Electronics',stage:'Contacted',next:'Product onboarding'}]:[{id:'LEAD-101',business:'Musanze Fashion Hub',contact:'+250 788 100 007',category:'Fashion',stage:'Interested',next:'Registration support'}]);
 return <DashboardLayout admin><Header eyebrow="MVEC GROWTH" title={supplier?'Supplier acquisition':'Vendor acquisition'} desc={supplier?'Build supplier relationships and help businesses bring their inventory onto MVEC.':'Track assisted vendor onboarding and help businesses start selling through MVEC.'}/><div className="dash-grid acquisition-grid"><div className="data-card"><h3>{supplier?'Supplier value proposition':'Vendor value proposition'}</h3><p>{supplier?'MVEC connects your inventory with businesses looking for products, creating a wider route to market and organized supply orders.':'Start selling through MVEC without building a separate e-commerce platform. Vendors receive a digital store, customers, payment infrastructure, delivery support, marketing opportunities and analytics.'}</p><div className="flow-box">{(supplier?['Business','Join MVEC','List products','Reach vendors','Receive supply orders','Sell more']:['Business','Register','Create store','Upload products','Reach buyers','Start selling']).map((x,i)=><span key={x}>{i>0&&'↓ '}{x}</span>)}</div></div><div className="data-card"><h3>Acquisition pipeline</h3><SmartTable columns={[{key:'business',label:'Business'},{key:'contact',label:'Contact'},{key:'category',label:'Category'},{key:'stage',label:'Stage'},{key:'next',label:'Next step'}]} rows={rows} rowKey={r=>r.id} searchPlaceholder="Search businesses…"/></div></div></DashboardLayout>
}

export function RiskManagement(){
 const rows=read('mvec_risk_flags',[{id:'RISK-1001',type:'Affiliate',party:'AFF-00045',signal:'Self-referral pattern',risk:'High',status:'Flagged'},{id:'RISK-1002',type:'Payment',party:'MVEC-TXN-2026-0021',signal:'Unusual transaction pattern',risk:'Medium',status:'Review'},{id:'RISK-1003',type:'Vendor',party:'Kigali Tech Store',signal:'Repeated cancellations',risk:'Low',status:'Monitoring'}]);
 return <DashboardLayout admin><Header eyebrow="SECURITY · RISK" title="Fraud & risk management" desc="Review suspicious payments, accounts, orders, refunds and affiliate activity."/><div className="metric-grid"><Metric label="High risk" value={rows.filter(r=>r.risk==='High').length} sub="Needs action" icon="bell"/><Metric label="Under review" value={rows.filter(r=>r.status==='Review').length} sub="Open cases" icon="chart"/><Metric label="Monitoring" value={rows.filter(r=>r.status==='Monitoring').length} sub="Watch list" icon="users"/></div><div className="data-card"><SmartTable columns={[{key:'id',label:'Risk ID'},{key:'type',label:'Area'},{key:'party',label:'Party'},{key:'signal',label:'Signal'},{key:'risk',label:'Risk',render:r=><span className={'status '+(r.risk==='High'?'warning':'active')}>{r.risk}</span>},{key:'status',label:'Status'}]} rows={rows} rowKey={r=>r.id} searchPlaceholder="Search risk cases…"/></div></DashboardLayout>
}

export function LanguageSettings(){
 const {translations,custom,updateTranslation}=useLanguage();
 const [lang,setLang]=useState('en');
 const keys=Object.keys(translations.en);
 return <DashboardLayout admin><Header eyebrow="PLATFORM · LANGUAGES" title="Language management" desc="Manage the marketplace language options and translation keys."/><div className="data-card"><div className="language-admin-head"><div><h3>Translation keys</h3><span>Changes are saved for the selected language.</span></div><select className="period-select" value={lang} onChange={e=>setLang(e.target.value)}><option value="en">English</option><option value="rw">Kinyarwanda</option><option value="fr">Français</option></select></div><div className="translation-list">{keys.map(key=><label className="translation-row" key={key}><span><b>{key}</b><small>English: {translations.en[key]}</small></span><input value={custom[lang]?.[key]||translations[lang]?.[key]||''} onChange={e=>updateTranslation(lang,key,e.target.value)} placeholder={translations.en[key]}/></label>)}</div></div></DashboardLayout>;
}
