import {Link,useParams} from "react-router-dom";
import {useEffect,useState} from "react";
import Storefront from "../components/Storefront";
import {demoOrders,products} from "../data";
import {calculateCommission,cancelOrderByBuyer,getDeliveryRemaining,getOrders,releaseSettlement,updateOrder,syncOrderLifecycle} from "../services/mvecStore";
import {useToast} from "../components/Toast";
const money=n=>new Intl.NumberFormat("en-RW").format(Number(n)||0)+" RWF";
const fmt=ms=>{const s=Math.max(0,Math.floor(ms/1000));const h=Math.floor(s/3600),m=Math.floor((s%3600)/60),sec=s%60;return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`};
const canCancel=o=>o.payment==='SUCCESS'&&o.refundStatus!=='FULL'&&o.status!=='Cancelled'&&o.paidAt&&Date.now()-new Date(o.paidAt).getTime()<=30*60*1000;
export default function OrderDetails(){
 const {id}=useParams();const toast=useToast();const [tick,setTick]=useState(0),[reported,setReported]=useState(false),[reason,setReason]=useState(""),[review,setReview]=useState(""),[message,setMessage]=useState("");
 useEffect(()=>{const t=setInterval(()=>{syncOrderLifecycle();setTick(x=>x+1)},1000);return()=>clearInterval(t)},[]);
 const local=getOrders().find(x=>String(x.id)===String(id));const order=local||demoOrders.find(x=>String(x.id)===String(id))||demoOrders[0];
 const item=order.items?.[0],p=products.find(x=>String(x.id)===String(item?.productId))||products.find(x=>x.vendor===order.vendor)||products[0];
 const statusList=["Created","Payment Confirmed","Preparing","Shipped","Out for Delivery","Delivered","Completed"];const idx=Math.max(0,statusList.indexOf(order.status));const remaining=getDeliveryRemaining(order);
const report=()=>{if(!reason)return;updateOrder(order.id,{disputeStatus:"open",disputeReason:reason});setReported(true);toast.success("Problem reported. MVEC support can review the order.")};
  const reviewOrder=()=>{if(review.trim()){updateOrder(order.id,{review:review.trim(),reviewStatus:"submitted"});toast.success("Review submitted. Thanks for your feedback!")}};
  const cancel=()=>{try{cancelOrderByBuyer(order.id);const m="Order cancelled successfully. A full refund has been recorded.";setMessage(m);toast.success(m)}catch(e){setMessage(e.message);toast.error(e.message)}};
 return <Storefront><main className="account-page"><div className="page-title"><span className="eyebrow">ORDER DETAILS</span><h1>{order.id}</h1><p>{item?.name||p.name} · {order.date}</p></div>
 {message&&<div className="form-alert success">{message}</div>}
 <div className="detail-grid"><section className="data-card"><div className="data-card-head"><div><h3>Order information</h3><span>{order.date}</span></div><em className="status active">{order.status}</em></div><div className="order-product"><img src={p.image} alt=""/><div><b>{item?.name||p.name}</b><small>{p.sku} · Qty {item?.qty||1}</small><strong>{money(order.total)}</strong></div></div><div className="order-summary-lines"><span>Products <b>{money(order.subtotal||order.total)}</b></span><span>Shipping <b>{money(order.shipping||0)}</b></span><span className="grand">Grand total <b>{money(order.total)}</b></span></div></section>
 <section className="data-card"><h3>Seller & payment</h3><div className="profile-detail"><b>{order.vendor}</b><span>MVEC Verified seller ✓</span><span>Payment: {order.payment||"PENDING"}</span><span>Method: {order.paymentMethod||"Not selected"}</span><span>Settlement: {order.settlementStatus==="RELEASED"?"Released to seller":order.payment==="SUCCESS"?"Funds held by MVEC":"Not funded"}</span></div><h3 className="subhead">MVEC commission</h3><span>{money(order.commission||calculateCommission(order.subtotal||order.total))} recorded as marketplace commission</span></section></div>
 {order.payment==='SUCCESS'&&order.settlementStatus==='HELD'&&<section className="data-card countdown-card"><div className="data-card-head"><div><h3>Delivery countdown</h3><span>Three hours from successful payment</span></div><strong className={remaining<15*60*1000?'danger-text':''}>{fmt(remaining)}</strong></div><p>{remaining>0?"Your order must be delivered and confirmed before this timer expires.":"The delivery window has expired. The order is being cancelled and a full refund is being recorded."}</p>{canCancel(order)&&<button className="outline-btn" onClick={cancel}>Cancel order · full refund</button>}</section>}
 {order.payment==='SUCCESS'&&order.buyerDeliveryOtp&&order.settlementStatus==='HELD'&&<section className="verified-box otp-buyer-box"><b>🔐 Your delivery OTP</b><p>Give this code only to the delivery person when your order arrives. The order is marked delivered only after the correct code is entered.</p><strong className="delivery-otp">{order.buyerDeliveryOtp}</strong>{order.deliveryOtpVerified&&<span className="success-text">Delivery OTP verified ✓</span>}</section>}
 {order.refundStatus==='FULL'&&<section className="verified-box refund-box"><b>Full refund recorded</b><p>Refund amount: <strong>{money(order.refundAmount)}</strong>. Reason: {order.refundReason||"Order cancellation"}.</p></section>}
 <section className="data-card"><div className="data-card-head"><div><h3>Delivery timeline</h3><span>Delivery status updates automatically.</span></div></div><div className="timeline">{statusList.map((s,i)=><div className={i<=idx?"timeline-item done":"timeline-item"} key={s}><i/><div><b>{s}</b><small>{i===idx?"Current order status":"MVEC workflow step"}</small></div></div>)}</div>{order.deliveryOtpVerified&&<div className="verified-box"><b>✓ Delivery proof recorded</b><p>The delivery OTP was verified successfully. Protected funds can now be released.</p></div>}</section>
 {(order.status==="Delivered"||order.status==="Completed")&&<section className="data-card"><h3>Leave a review</h3><textarea className="field" value={review} onChange={e=>setReview(e.target.value)} placeholder="Tell other buyers about your experience…"/><button className="gradient-btn" onClick={reviewOrder}>Submit review</button></section>}
 <section className="data-card"><h3>Report a problem</h3>{reported?<div className="form-alert success">Your problem was reported. MVEC support can review the order and evidence.</div>:<><select className="field" value={reason} onChange={e=>setReason(e.target.value)}><option value="">Choose a problem</option><option>Product not received</option><option>Wrong product</option><option>Damaged product</option><option>Missing item</option><option>Product differs from description</option><option>Other</option></select><button className="outline-btn" onClick={report}>Report a problem</button></>}</section>
 <Link className="outline-btn" to="/orders">← Back to orders</Link></main></Storefront>}
