import {useMemo,useState} from "react";
import Icon from "./Icon";
import Pagination from "./Pagination";
const money=n=>new Intl.NumberFormat("en-RW").format(Number(n)||0)+" RWF";
const steps=["Order placed","Payment confirmed","Preparing","Ready for shipment","Shipped","Out for delivery","Delivered"];
const STATUS_INDEX={PENDING:0,CONFIRMED:1,PROCESSING:2,READY_FOR_SHIPMENT:3,SHIPPED:4,OUT_FOR_DELIVERY:5,DELIVERED:6,COMPLETED:6};
const TERMINAL={CANCELLED:"Cancelled",RETURNED:"Returned",REFUNDED:"Refunded",FAILED:"Failed"};
const fmtDate=d=>{if(!d)return "—";const dt=new Date(d);return isNaN(dt.getTime())?"—":dt.toLocaleDateString("en-GB")};
export default function DeliveryTracking({orders=[],role="vendor"}){
 const [q,setQ]=useState("");const [page,setPage]=useState(1);const perPage=5;
 const roleOrders=role==="supplier"?orders.filter(o=>o.supplierId||o.orderType==="supplier"):role==="vendor"?orders.filter(o=>o.items&&o.items.some(it=>it.vendor)):role==="affiliate"?orders.filter(o=>o.affiliateCode):orders;
 const filtered=useMemo(()=>roleOrders.filter(o=>JSON.stringify(o).toLowerCase().includes(q.toLowerCase())),[roleOrders,q]);const shown=filtered.slice((page-1)*perPage,page*perPage);
 return <><div className="dash-page-head"><div><span className="eyebrow">DELIVERY & SETTLEMENT</span><h1>{role==='admin'?'All deliveries':'Delivery tracking'}</h1><p>Track delivery progress and the final delivery confirmation.</p></div></div>
 <div className="verified-box settlement-banner"><b>Paid orders</b><p>Delivery is confirmed only when the buyer's delivery OTP is verified. After successful verification the protected amount is released according to the settlement rules.</p></div>
 <div className="dash-toolbar"><div className="dash-filter"><Icon name="search"/><input value={q} onChange={e=>{setQ(e.target.value);setPage(1)}} placeholder="Search order, product, customer or vendor…"/></div></div>
 <div className="data-card"><div className="data-card-head"><div><h3>Delivery operations</h3><span>{filtered.length} orders</span></div></div>
 {shown.map(o=>{const idx=STATUS_INDEX[o.orderStatus]??(o.orderStatus?0:0);const terminal=TERMINAL[o.orderStatus];return <div className="delivery-track-card" key={o._id||o.orderNumber}><div className="delivery-track-head"><div><b>{o.orderNumber||o._id}</b><small>{o.items?.[0]?.name||"Order"}</small><small>{o.user?.Fullname||"Buyer"} · {o.items?.[0]?.vendor?.companyName||o.items?.[0]?.vendor?.Fullname||"Marketplace seller"}</small></div><div className="settlement-chip"><span className={o.orderStatus==="DELIVERED"||o.orderStatus==="COMPLETED"?'released':'held'}>{o.orderStatus==="DELIVERED"||o.orderStatus==="COMPLETED"?'Delivered':'Order total'}</span><strong>{money(o.totalAmount)}</strong></div></div>{terminal?<p className="form-alert error">Order {terminal.toLowerCase()}.</p>:<div className="delivery-steps">{steps.map((s,i)=><div className={i<=idx?'step done':'step'} key={s}><i>{i<idx?'✓':i===idx?'●':''}</i><small>{s}</small></div>)}</div>}<div className="delivery-track-actions"><span>Payment: <b>{o.paymentStatus}</b></span><span>{o.statusText||(o.deliveredAt?"Delivered: ":"Placed: ")+fmtDate(o.deliveredAt||o.createdAt)}</span><span>OTP: <b>{o.deliveryOtp?o.isDelivered?'Verified ✓':'Awaiting delivery verification':'Not generated'}</b></span></div>{!terminal&&<p className="tiny delivery-note">The delivery person must obtain the buyer's OTP at the door. The correct OTP confirms delivery for both sides and triggers the settlement release.</p>}</div>})}
 {!shown.length&&<div className="empty-state"><h3>No deliveries to track</h3><p>Orders will appear here once passed in.</p></div>}<Pagination page={Math.min(page,Math.max(1,Math.ceil(filtered.length/perPage)))} setPage={setPage} total={filtered.length} perPage={perPage}/></div></>;
}