import {Link,useNavigate} from 'react-router-dom';
import {useState,useEffect} from 'react';
import Icon from './Icon';
import {useAuth} from '../context/AuthContext';
import {useTheme} from '../context/ThemeContext';
import {useMarketplace} from '../context/MarketplaceContext';
import {useLanguage} from '../context/LanguageContext';
import {loadCatalog} from '../services/catalogApi';
import {getCatalogProducts} from '../services/mvecStore';
import {rankCatalogProducts} from '../services/searchService';

const allCategories=['Electronics','Phones','Computers','Fashion','Home & Living','Beauty','Health & Personal Care','Groceries','Food & Beverages','Baby & Kids','Sports & Fitness','Automotive','Agriculture','Tools & Hardware','Furniture','Appliances','Books & Stationery','Jewelry & Accessories','Shoes & Bags','Toys & Games','Pet Supplies','Office Supplies','Construction Materials','Garden & Outdoor','Services'];
export default function Storefront({children}){
 const {user,logout}=useAuth();const {theme,toggleTheme}=useTheme();const {cartCount,wishlistCount}=useMarketplace();const {language,setLanguage,t}=useLanguage();const navigate=useNavigate();const [search,setSearch]=useState('');const [catOpen,setCatOpen]=useState(false);
 const [catalog,setCatalog]=useState({products:[],vendors:[]});
 useEffect(()=>{let mounted=true;loadCatalog().then(cat=>{if(!mounted)return;setCatalog({products:cat.products||[],vendors:cat.vendors||[]});});return()=>{mounted=false};},[]);
 const catalogProducts=getCatalogProducts(catalog.products);
 const notificationPath=user?.role==='vendor'?'/vendor/notifications':user?.role==='supplier'?'/supplier/notifications':user?.role==='affiliate'?'/affiliate/notifications':user?.role==='super_admin'?'/admin/notifications':'/buyer/notifications';
 const s=search.trim().toLowerCase();
 const ranked=rankCatalogProducts(catalogProducts,{q:search});
 const suggestions=ranked.results.slice(0,6);
 const categorySuggestions=search.trim()?allCategories.filter(c=>{
   const cl=c.toLowerCase();
   return cl.includes(s)||s.split(/\s+/).filter(w=>w.length>=3).some(w=>cl.includes(w)||w.includes(cl)&&cl.length>2);
 }).slice(0,3):[];
 const vendorSuggestions=search.trim()?catalog.vendors.filter(v=>`${v.name} ${v.category}`.toLowerCase().includes(s)).slice(0,3):[];
 const relatedIds=new Set((ranked.related||[]).map(p=>String(p.id)));
 const submitSearch=()=>{if(search.trim())navigate(`/shop?q=${encodeURIComponent(search.trim())}`)};
 const onSearchKey=e=>{if(e.key==='Enter')submitSearch()};
 return <>
 <header className="top-strip"><div>Welcome to <b>MVEC</b> — Rwanda's multi-vendor marketplace</div><div className="top-links"><Link to="/buyer/support">{t('help')}</Link><Link to="/signup">{t('becomeVendor')}</Link><select className="language-select" value={language} onChange={e=>setLanguage(e.target.value)} aria-label="Language"><option value="rw">Kinyarwanda</option><option value="en">English</option><option value="fr">Français</option></select></div></header>
 <header className="market-header"><Link to="/" className="mvec-brand">MVEC</Link><div className="market-search-wrap"><div className="market-search"><Icon name="search"/><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={onSearchKey} placeholder={`${t('search')} products, brands, vendors...`} aria-label={t('search')}/><select aria-label={t('allCategories')} onChange={e=>e.target.value&&navigate(`/shop?category=${encodeURIComponent(e.target.value)}`)}><option value="">{t('allCategories')}</option>{allCategories.map(c=><option key={c}>{c}</option>)}</select><button type="button" onClick={submitSearch}>{t('search')}</button></div>{search.trim()&&<div className="global-search-results">{categorySuggestions.map(c=><Link key={`c-${c}`} to={`/shop?category=${encodeURIComponent(c)}`} onClick={()=>setSearch('')}><span className="search-avatar">▦</span><span><b>{c}</b><small>Browse {c}</small></span></Link>)}{suggestions.map(p=><Link key={`p-${p.id}`} to={`/product/${p.id}`} onClick={()=>setSearch('')}><img src={p.image} alt=""/><span><b>{p.name}</b><small>{p.category} · {new Intl.NumberFormat('en-RW').format(p.price)} RWF{relatedIds.has(String(p.id))?' · Related':''}</small></span></Link>)}{vendorSuggestions.map(v=><Link key={`v-${v.id}`} to={`/vendors/${v.id}`} onClick={()=>setSearch('')}><span className="search-avatar">{v.name[0]}</span><span><b>{v.name}</b><small>Vendor · {v.category}</small></span></Link>)}{!suggestions.length&&!vendorSuggestions.length&&!categorySuggestions.length&&<div className="search-no-results">No matching products or vendors</div>}<button type="button" className="search-view-all" onClick={submitSearch}>View all results</button></div>}</div>
 <div className="header-actions"><button className="site-theme-toggle" onClick={toggleTheme} title="Toggle theme" aria-label="Toggle theme"><Icon name={theme==='dark'?'sun':'moon'} size={18}/></button><Link className="count-link" to="/wishlist" title="Wishlist"><Icon name="heart"/><span className="nav-count">{wishlistCount}</span></Link>{user&&<Link className="count-link notification-link" to={notificationPath} title="Notifications" aria-label="Notifications"><Icon name="bell"/><span className="notification-dot"/></Link>}<Link className="count-link" to="/cart" title="Cart"><Icon name="cart"/><span className="nav-count">{cartCount}</span></Link>{user?<div className="user-menu"><Link to="/profile"><Icon name="user"/><span>{user.fullName?.split(' ')[0]}</span></Link><button onClick={logout} title="Logout"><Icon name="logout"/></button></div>:<Link className="login-link" to="/login">{t('signIn')}</Link>}</div></header>
 <nav className="main-nav"><div className="category-menu category-menu-dropdown"><button type="button" onClick={()=>setCatOpen(v=>!v)}><Icon name="menu"/><span>{t('allCategories')}</span></button>{catOpen&&<div className="category-dropdown">{allCategories.map(c=><Link onClick={()=>setCatOpen(false)} key={c} to={`/shop?category=${encodeURIComponent(c)}`}>{c}</Link>)}</div>}</div><div className="main-nav-links"><Link to="/"><Icon name="home"/><span>{t('home')}</span></Link><Link to="/shop"><Icon name="shop"/><span>{t('shop')}</span></Link><Link to="/buyer/recommendations"><Icon name="heart"/><span>{t('forYou')}</span></Link><Link to="/shop?deal=true"><Icon name="tag"/><span>{t('deals')}</span></Link><Link to="/vendors"><Icon name="users"/><span>{t('vendors')}</span></Link><Link to="/orders"><Icon name="box"/><span>{t('orders')}</span></Link></div>{user?.role==='vendor'&&<Link className="nav-admin" to="/vendor">Dashboard</Link>}{user?.role==='supplier'&&<Link className="nav-admin" to="/supplier">Dashboard</Link>}{user?.role==='affiliate'&&<Link className="nav-admin" to="/affiliate">Dashboard</Link>}{user?.role==='super_admin'&&<Link className="nav-admin" to="/admin">Dashboard</Link>}</nav>
 {children}<footer className="market-footer"><div><div className="mvec-brand footer-brand">MVEC</div><p>Multi-vendor commerce built for buyers and sellers across Rwanda.</p></div><div><h4>Marketplace</h4><Link to="/shop">Shop</Link><Link to="/vendors">Stores</Link><Link to="/wishlist">Wishlist</Link></div><div><h4>Customer service</h4><Link to="/profile">My account</Link><Link to="/orders">Orders</Link><Link to="/buyer/support">Help & Support</Link><Link to="/login">Sign in</Link></div><div><h4>Sell on MVEC</h4><Link to="/signup">Become a vendor</Link><Link to="/vendor">Dashboard</Link></div></footer></>
}
